language: c

sudo: false

os:
  - linux
  - osx

compiler:
  - gcc
  - clang

addons:
  apt:
    packages:
      - automake
      - autoconf
      - libtool
      - swig
      - lua5.2

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install automake autoconf libtool swig lua; fi

env:
  matrix:
      - LUA=lua5.3
      - CC="/usr/bin/gcc -L/usr/local/lib -llua" && ./configure --with-xml-support --with-lua-binding

script:
  - autogen.sh
  - make
  - make install
