language: c

sudo: required

cache:
  directories:
  - "$HOME/opt"

os:
  - linux
  - osx

compiler:
  - gcc
  - clang

addons:
  apt:
    packages:
      - automake
      - autoconf
      - texinfo
      - libtool
      - swig
      - lua5.2

install: true

before_install:
  - export PATH=$HOME/opt/bin:$PATH
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install automake autoconf texinfo libtool swig lua; fi

env:
  matrix:
      - CC="/usr/bin/gcc -L/usr/local/lib -llua" && ./configure --with-xml-support --with-lua-binding

script:
  - ./autogen.sh
  - make && make install
